### PR TITLE
Re-Add Avaje Spi to Extension spi

### PR DESCRIPTION
**Pull request by SentryMan**
It is required

### CODE REVIEW

**Comment by SentryMan** [comment]
@rbygrave observe that the build fails without spi

**Comment by rbygrave** [comment]
> @rbygrave observe that the build fails without spi

Huh? It didn't fail though?

**Comment by SentryMan** [comment]
See the checks of the previous commit

**Comment by SentryMan** [comment]
image

**Comment by rob-bygrave** [comment]
Which build? The only broken builds are on this branch where it is being re-added? Can you link to the build

**Comment by SentryMan** [comment]
https://github.com/avaje/avaje-jsonb/actions/runs/9670850783/job/26680352438

**Comment by SentryMan** [comment]
the broken part wasn't when it was being re-added, it was when I added a test using `@ServiceProvider` on `CustomTypeComponent` to test the functionality instead of manually registering.

**Comment by rbygrave** [comment]
> I added a test using @ServiceProvider on CustomTypeComponent to test the functionality instead of manually registering.

Yes, I see that now. This could also be considered a bug in avaje-spi-service - it can be fixed there via a change to that ServiceProcessor EXEMPT_SERVICES logic.  As in, the current spi ServiceProcessor needs the `@Service` placeholder in order to get the correct interface tested against the EXEMPT_SERVICES.

Hmm.

**Comment by SentryMan** [comment]
> Yes, I see that now. This could also be considered a bug in avaje-spi-service 

possibly, but I don't want to change avaje spi service every time we make a new interface that extends JsonbException and the like.

**Comment by SentryMan** [comment]
There's a bunch of edge cases we might have to deal if we go that route.

**Comment by rob-bygrave** [comment]
> There's a bunch of edge cases we might have to deal if we go that route.

What would be an example?  To me I'm thinking that we have logic on the 2 sides / 2 APs where on one side it uses exclude via isAssignable check and on the spi-service side it's service interface in the EXEMPT_SERVICES [so right now effectively those 2 sides don't match each other].  Adding the `@Service` marker means they match up by spi-service now getting that the service interface type to match the isAssignable check.

What sort of edge cases are there?

**Comment by rbygrave** [comment]
Updated the description and title and included the description in the commit message.

**Pull request merged**
