### PR TITLE
Change name hash from long to int

### PR DESCRIPTION
**Pull request by rbygrave**

### CODE REVIEW

**Comment by rbygrave** [comment]
I think the benchmarking is also hinting that switching on int hash values (skipping the known keys lookup) would be a significant performance improvement. Generating code that switched on hash values would be ok for the built in Json streaming / parsing but not best for Jackson. That is, doing that optimisation might be an opt-in that prevents the use of the jackson-core parser.

**Comment by SentryMan** [comment]
Does it just make it slower, or actually prevent the use of Jackson?

**Review by SentryMan — APPROVED** [review]

**Comment by SentryMan** [comment]
Can I see some of the benchmarks?

**Comment by rbygrave** [comment]
```
java -jar target/bench-jmh.jar RecordBasicTest -i 3 -t 3 -f 1

-- BEFORE --

Benchmark                                          Mode  Cnt      Score      Error   Units
RecordBasicTest.fromJson_wideNames_dsl            thrpt    3  13333.503 ± 1265.854  ops/ms
RecordBasicTest.fromJson_wideNames_jsonb_diesel   thrpt    3   6642.972 ±  365.300  ops/ms
RecordBasicTest.fromJson_wideNames_jsonb_jackson  thrpt    3   5590.459 ±  589.175  ops/ms
RecordBasicTest.fromJson_wideNames_objectMapper   thrpt    3   5546.227 ±  541.145  ops/ms

-- AFTER / With this change --

Benchmark                                          Mode  Cnt      Score      Error   Units
RecordBasicTest.fromJson_wideNames_dsl            thrpt    3  13267.107 ±  887.453  ops/ms
RecordBasicTest.fromJson_wideNames_jsonb_diesel   thrpt    3   9741.978 ±   96.255  ops/ms
RecordBasicTest.fromJson_wideNames_jsonb_jackson  thrpt    3   6185.965 ±  224.880  ops/ms
RecordBasicTest.fromJson_wideNames_objectMapper   thrpt    3   5669.367 ± 1297.524  ops/ms
```

So for this benchmark it improves from `6642.972` -> `9741.978`


> Does it just make it slower, or actually prevent the use of Jackson?

I have not yet made the change to test out that switch change. I expect it to be a make the jsonb + Jackson core a little slower.

**Comment by SentryMan** [comment]
When I ran this on the java json benchmark the performance was decreased

**Comment by rbygrave** [comment]
A prototype of the switch on int hash does show it faster (and breaks jsonb_jackson):

```
Benchmark                                         Mode  Cnt      Score     Error   Units
RecordBasicTest.fromJson_wideNames_dsl           thrpt    3  13306.355 ±  10.741  ops/ms
RecordBasicTest.fromJson_wideNames_jsonb_diesel  thrpt    3  11375.393 ±  16.592  ops/ms
RecordBasicTest.fromJson_wideNames_objectMapper  thrpt    3   5764.986 ± 296.773  ops/ms
```

From `9741.978` -> `11375.393`

**Comment by rbygrave** [comment]
> When I ran this on the java json benchmark the performance was decreased

Ok, I'll have a look and see if I also see that.

**Comment by SentryMan** [comment]
you can run the java json benechmark on JDK 21 by building the jar with `./gradlew clean build shadowJar` on jdk 17, then running the generated jar on JDK 21

**Comment by rbygrave** [comment]
Updated benchmark:

```
Benchmark                             Mode  Cnt        Score       Error  Units
Deserialization.avajejsonb           thrpt    5  4624731.680 ± 25754.476  ops/s
Deserialization.avajejsonb_jackson   thrpt    5  4199734.301 ± 20832.600  ops/s
Deserialization.dsljson              thrpt    5  6287913.440 ± 11831.706  ops/s
Deserialization.dsljson_reflection   thrpt    5  2061309.610 ±  7301.957  ops/s
Deserialization.jackson              thrpt    5  3434177.596 ±  3602.316  ops/s
Deserialization.jackson_afterburner  thrpt    5  3734607.440 ±  4378.507  ops/s
Deserialization.jackson_blackbird    thrpt    5  3683341.892 ± 12777.408  ops/s
```

**Comment by SentryMan** [comment]
Got a before and after comparison?

**Comment by rob-bygrave** [comment]
> Got a before and after comparison?

Hmm, I wonder if it would be an idea to have a GitHub workflow to run a benchmark periodically or on demand?
I wonder if the benchmark we have here is not meaty enough, should be more like [java-json-benchmark](https://github.com/fabienrenaud/java-json-benchmark) or a copy of some of it?  

NB: It might be my local but the benchmark runs seem more consistent / predictable using Java 17 compared to Java 21 benchmark runs.

**Pull request merged**
