### PR TITLE
More Sonar Fixes

### PR DESCRIPTION
**Pull request by SentryMan**

### CODE REVIEW

**Comment by rbygrave** [comment]
This PR includes changes I'm not comfortable with. I'll look to apply the changes that we can later.

**Comment by SentryMan** [comment]
> This PR includes changes I'm not comfortable with. I'll look to apply the changes that we can later.

elaborate??

**Comment by rob-bygrave** [comment]
The diff of NumberParser isn't humanly parsable without excessively high levels of coffee - it does too much.

**Comment by SentryMan** [comment]
We'll have to get to it eventually, but sure I can take those out

**Comment by rob-bygrave** [comment]
Replaced this with https://github.com/avaje/avaje-jsonb/pull/202 - Sorry, I should have been clearer ... I wasn't happy with the diff for NumberParser and wanted any changes to NumberParser to be done nicely, clearly, slowly etc.

I've pulled the other changes into 202 and merged that.

**Pull request closed without merging**
