### PR TITLE
Add JsonOutput to optimise writing to Nima ServerResponse

### PR DESCRIPTION
**Pull request by rbygrave**
For Nima its used like:

```java
// given response is a Nima Http ServerResponse

jsonType.toJson(result, JsonOutput.of(response));
```

### CODE REVIEW

**Comment by SentryMan** [comment]
can we do something wild with multi-release jars to support 17?

**Comment by rbygrave** [comment]
> does this mean that jsonb can only work on 19+?

No, it will work with Java 11+.  The compilation target is still 11.

BUT ... anyone **_building it_** needs to build using JDK 19 due to the optional dependency to Nima and anyone using JsonOutput.of(nimaResponse) is already using 19.

**Comment by rbygrave** [comment]
The alternative would be to pull out NimaJsonOutput into it's own module ... but I'm not too keen on that.

**Comment by SentryMan** [comment]
Sounds good, I'll pull the pr and debug on my local to confirm there is no array copy.

**Comment by SentryMan** [comment]
LGTM

**Pull request merged**
